config/routes.rb
Rails.application.routes.draw do

  root                  'static_pages#home'
  get    'signup'   =>  'users#new'
  get    'login'    =>  'sessions#new'
  post   'login'    =>  'sessions#create'
  delete 'logout'   =>  'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,   only: [:create, :destroy]

  resources :courses

  resources :lessons do
    resources :words
  end

  resources :words
  resources :results, only: [:show]

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :logged_in_user, only: [:new, :edit, :update, :index, :show]
  before_action :admin_user,     only: [:new, :edit, :update, :destroy]

  def index
    @courses = Course.paginate page: params[:page]
  end

  def show
    @course = Course.find params[:id]
    @lessons = @course.lessons_learned_by_user current_user.id
  end

  def new
    @course = Course.new
    @lesson = @course.lessons.build
    @word = @course.words.build
    4.times {@word.choices.build}
  end

  def create
    @course = Course.new course_params
    if @course.save
      flash[:success] = "New course has been created!"
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find params[:id]
  end

  def update
    @course = Course.find params[:id]
    if @course.update_attributes course_params
      flash[:success] = "Course updated"
      redirect_to courses_path
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find params[:id]
    @course.destroy
    flash[:success] = "Course deleted"
    redirect_to request.referrer || root_url     
  end

  private
    def course_params
      params.require(:course).permit :name, :content, lessons_attributes: [:course_id, :name], words_attributes: [:course_id, :word, :translation, choices_attributes: [:word_id, :choice]]
    end  

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end      
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div class = "course_item">
  <div class = "item_header">
    <%= link_to course.name, course %>
    <span>
      <%= link_to "Edit", edit_course_path(course) %> 
      | <%= link_to "delete", course, method: :delete,
                                    data: {confirm: "You sure?"} %>   
    </span>     
  </div>
  <div class = "item_content">
    <%= course.content %>
  </div>
</div>

app/views/courses/_course_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<h3> Course: </h3>
<div class = "field">
  <%= f.text_field :name, placeholder: "course name", class: "form-control" %>
</div>
<div class="field">
  <%= f.text_field :content, placeholder: "course content", class: "form-control" %>
</div>

<h3> Lesson of course </h3>
<%= f.fields_for :lessons do |ff| %>
  <%= render 'lesson_fields', f: ff %>
<% end %>

<h3> Word of course </h3>
<%= f.fields_for :words do |ff| %>
  <%= render 'word_fields', f: ff %>

  <h3> Choices: </h3>
  <%= ff.fields_for :choices do |builder| %>
    <%= render 'word_choice_fields', ff: builder %>
  <% end %>
<% end %>

app/views/courses/_lesson_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label 'Lesson name' %>
<%= f.text_field :name, class: 'form-control' %>

app/views/courses/_word_choice_fields.html.erb
<div class="fields">
  <p>
    <%= ff.label :choice %>
    <%= ff.text_field :choice, class: "form-control" %>
  </p>
</div>

app/views/courses/_word_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label 'Word name' %>
<%= f.text_field :word, class: 'form-control' %>
<%= f.label 'Translation' %>
<%= f.text_field :translation, class: 'form-control' %>

app/views/courses/edit.html.erb
<% provide(:title, 'Edit course') %>

<div class = "col-md-8 col-md-offset-2">
  <%= form_for(@course) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class = "field">
      <%= f.text_field :name, placeholder: "course name", class: "form-control" %>
    </div>
    <div class="field">
      <%= f.text_field :content, placeholder: "course content", class: "form-control" %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/courses/index.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'users/follow_form' %>    
      </section>    
      <% if admin_user? %>
        <p><%= link_to "New Course", new_course_path %></p>
      <% end %>          
    </aside>
    <div class="col-md-8">
      <%= render 'shared/words_lessons_link' %>
      <div class = "activities">
        <div class = "all_courses">All Courses</div>
        <hr />
        <%= will_paginate %>

		<div class="courses">
		  <%= render @courses %>
		</div>
      </div>
    </div>  
  </div>
<% else %>


  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  
  <%= link_to image_tag("rails.png", alt: "Rails logo"),
              'http://rubyonrails.org/' %>
<% end %>

app/views/courses/new.html.erb
<% provide(:title, 'Make new course') %>

<div class = "col-md-8 col-md-offset-2">
  <%= form_for(@course) do |f| %>
    <%= render 'course_fields', f: f %>

    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/courses/show.html.erb
<div class = "course_item">
  <div class = "item_header">
    <%= @course.name %>
  </div>
  <div class = "item_content">
    <%= @course.content %>
  </div>
  <div class = "list-lessons">
    <ul>
      <% @lessons.each do |lesson| %>
        <% if lesson.finished? %>
          <li>
            <%= link_to "Lesson #{lesson.id}", lesson_path(lesson) %>
            <%= "(finished)" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Lesson #{lesson.id}", lesson_word_path(lesson.id,
                                             lesson.first_remain_word.id) %>
            <%= "(#{lesson.num_of_submitted_words}/#{lesson.learned_words.count})" %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>